### ISSUE TITLE
Question: Output from Assembly not writing out to go code

### ISSUE THREAD

**Issue by osok** [lesnuages/go-execute-assembly#5]
There is one thing that I could not understand from the original code base, and the problem carries through to the new code I submitted in the recent pull request.

I do have some Console.WriteLine() in my assembly, but I don't get anything in the output of the assembly to the main.go.  C# is new for me, I'm making the assumption that Console.WriteLine() write to the stdout.  Ultimately, I want to capture the output of the assembly and return it in my code.

**Comment by lesnuages** [comment]
I fixed this one in your merge request. The issue was here for a while, I just forgot to merge @djhohnstein fix into this project (he actually made a PR that I merged last week). The basic issue was that I haven't identified a way to check whenever the hosting process should be killed back when I wrote this, but turns out you can monitor the thread state and kill the process when the remote thread is done.

Everything should work now. I'll probably also push some code to find the reflective loader offset automatically to avoid hard-coding it. I already wrote the code [here](https://github.com/BishopFox/sliver/blob/master/client/command/tasks.go#L447-L483), just need to integrate it into this project.
